### ISSUE TITLE
Возможности препроцессора в комбинации с БЕМ

### ISSUE THREAD

**Issue by frostbolt** [hrebtovadara/my-cats-hotel#3]
Использование scss это очень хорошо. Об необходимости использования bem можно спорить долго, но раз уж ты используешь — используй kpacuBo, примерно вот так:

Вот этот кусок кода 
 ```
.address {
    background-color: $color-block;
    padding: 35px 15px;
}

.address__item {
    margin-bottom: 26px;
}

.address__item:last-child {
    margin-bottom: 0;
}
```

Можно было бы переписать вот так:

```
.address {
    background-color: $color-block;
    padding: 35px 15px;

    &__item {
        margin-bottom: 26px;
    
        &:last-child {
            margin-bottom: 0;
        }
    }
}
```

https://github.com/hrebtovadara/my-cats-hotel/blob/fd6749f7ed7c62dd69f3e05df3a990b2a724963a/source/sass/blocks/address.scss#L6

**Comment by frostbolt** [comment]
Не уверен, но ты тут описываешь какой-то хедер внутри хедера, вообще выглядит как нарушение BEM, но я сильно не вдавался в подробности.

```scss
.header--with-js {
    height: 62px;
    background-color: $color-white;

    .header--toggle {
        display: none;
    }
    
    .nav-header__button--menu {
        display: block;
    }
}
```

Но тут тоже ты не воспользовалась одной из [базовых возможностей своего препроцессора](https://sass-lang.com/guide), а именно возможностью писать вложенные стили.

https://github.com/hrebtovadara/my-cats-hotel/blob/fd6749f7ed7c62dd69f3e05df3a990b2a724963a/source/sass/blocks/header.scss#L32

**Comment by frostbolt** [comment]
Тоже к использованию препроцессора, поэтому докину в этот тред 

Media-queries так же могут быть вложенными, в большинстве случаев так и следует делать, чтобы не искать стили элементов по всему проекту.

```scss

.general {
    /* ... */

    @media (min-width: $tablet-width) {
        width: 768px;
    }
    
    @media (min-width: $desktop-width) {
        width: 1366px;
    }
}
```

https://github.com/hrebtovadara/my-cats-hotel/blob/fd6749f7ed7c62dd69f3e05df3a990b2a724963a/source/sass/blocks/general.scss#L10
