### ISSUE TITLE
Заменить SCSS переменные на CSS

### ISSUE THREAD

**Issue by frostbolt** [hrebtovadara/my-cats-hotel#4]
В случае на проекте нет необходимости поддерживать устаревшие версии браузеров, рекомендую вместо SCSS переменных использовать родные [CSS Custom Properties](https://developer.mozilla.org/ru/docs/Web/CSS/Using_CSS_custom_properties) которые так кстати недавно включили в стандарт. 

Базовый пример:

```css
/* definition */

:root {
  --color-text: #333;
}

/* usage */

.my-class {
  color: var(--color-text);
}
```

https://github.com/hrebtovadara/my-cats-hotel/blob/fd6749f7ed7c62dd69f3e05df3a990b2a724963a/source/sass/style.scss#L66
