### ISSUE TITLE
Названия шрифтов следует хранить в переменных

### ISSUE THREAD

**Issue by frostbolt** [hrebtovadara/my-cats-hotel#8]
Часто повторяющиеся примитивы, такие как шрифты, цвета, брейкпоинты, возможно определения теней (список не полный), следует хранить в переменных.

Например:

```scss 
/* variables.scss */
:root {
  --font-primary: "Rubik", sans-serif;
}

/* nav-footer.scss */
.nav-footer__list {
    font-family: var(--font-primary);
}
```
https://github.com/hrebtovadara/my-cats-hotel/blob/fd6749f7ed7c62dd69f3e05df3a990b2a724963a/source/sass/blocks/nav-footer.scss#L2
